# Generated by Django 5.0.2 on 2024-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[(1, 'card'), (2, 'cash')], default=1, max_length=1, verbose_name='тип платежа'),
        ),
    ]
