# Generated by Django 5.0.2 on 2024-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_payment_id_payment_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='дата оплаты'),
        ),
    ]
