# Generated by Django 5.0.2 on 2024-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Статус платежа'),
        ),
    ]
