# Generated by Django 5.0.2 on 2024-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
