# Generated by Django 5.0.2 on 2024-02-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_link',
        ),
    ]
