# Generated by Django 5.0.2 on 2024-03-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed',
        ),
    ]
